#!/usr/bin/env python

import rospy
from math import pow, atan2, sqrt
from tf.transformations import *

import smach
import smach_ros
from smach_ros import SimpleActionState
from smach_ros import ServiceState

import threading

# Navigation
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from nav_msgs.msg import Odometry
from geometry_msgs.msg import Twist

# Manipulator 
from geometry_msgs.msg import Pose
from open_manipulator_msgs.msg import JointPosition
from open_manipulator_msgs.msg import KinematicsPose
from open_manipulator_msgs.srv import SetJointPosition
from open_manipulator_msgs.srv import SetKinematicsPose

# AR Markers
from ar_track_alvar_msgs.msg import AlvarMarker
from ar_track_alvar_msgs.msg import AlvarMarkers

# Darknet Ros
from darknet_ros_msgs.msg import BoundingBoxes
from darknet_ros_msgs.msg import BoundingBox

# Jsk
from geometry_msgs.msg import PoseArray, Pose
import tf

# Depth Camera
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
#import time

class getPoseOfTheObject(smach.State):
    def __init__(self):
        smach.State.__init__(self, outcomes=['succeeded', 'aborted'],
                                    output_keys=['output_object_pose'])

        self.namespace = rospy.get_param("~robot_name")
        self.detection_names = rospy.get_param('/darknet_ros/yolo_model/detection_classes/names')
        self.object_3dpose_sub = rospy.Subscriber('/cluster_decomposer/centroid_pose_array', PoseArray, self.jskRosMsgCallback)       
        self.listener = tf.TransformListener()
        self.trans = [0.0 , 0.0 , 0.0]
        self.OFFSET_FOR_GOAL_HEIGHT = 0.150
        self.last_jskdetect_time = rospy.get_rostime()

    def jskRosMsgCallback(self, msg):
        for i, pose in enumerate(msg.poses):
            if pose != Pose():                
                try:
                    (trans,rot) = self.listener.lookupTransform('om_with_tb3/base_link', 'yolo_output'+str(i), rospy.Time(0))
                    pos = pose.position
                    val = [round(pos.x,2), round(pos.y,2), round(pos.z,2), round(trans[0],2), round(trans[1],2) , round(trans[2],2)]
                    key = self.detection_names[i] 
                    if key == "bottle" :
                        #self.update_key(key, val)
                        #print 'Found key {} centroid_pos {} num{} TF_pose from base_link {} '.format(key, val, i, trans)
                        self.trans[0] = round(trans[0],2) #x axis
                        self.trans[1] = round(trans[1],2) #y axis
                        self.trans[2] = round(trans[2],2) #z axis
                        self.last_jskdetect_time = rospy.get_rostime() 
                except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
                    rospy.logwarn('there is no tf ')

    def execute(self, userdata):      
        #Wait for nearby object to be detected
        object_pose = Pose()

        while True :
            #rospy.sleep(0.01)
            object_pose.position.x = self.trans[0]
            object_pose.position.y = self.trans[1]
            object_pose.position.z = self.trans[2] 
            dist = math.sqrt(object_pose.position.x**2 + object_pose.position.y**2 + object_pose.position.z**2)
            jskobject_detect_duration = rospy.get_rostime().to_sec() - self.last_jskdetect_time.to_sec()
            
            if jskobject_detect_duration > 1 :
                rospy.logwarn('there is no object duration time %.2f', jskobject_detect_duration )
                continue
            if object_pose.position.x > 0.5 or dist > 0.7 :
                rospy.logwarn('Object is too far x,y,x %.2f, %.2f, %.2f  dist %.2f', \
                    object_pose.position.x,object_pose.position.y,object_pose.position.z, dist)
                continue 
            if dist < 0.1 :
                rospy.logwarn('Object is too short x,y,x %.2f, %.2f, %.2f  dist %.2f, D435 min dist is 10 cm', \
                    object_pose.position.x,object_pose.position.y,object_pose.position.z, dist)
                continue             
            break 

        object_pose.position.y = 0

        # need check this point
        if object_pose.position.y > 0:
            yaw = math.acos(object_pose.position.x / dist)
        else:
            yaw = (-1) * math.acos(object_pose.position.x / dist)
        
        yaw = 0.0
        roll = 0.0
        pitch = 0.0

        cy = math.cos(yaw * 0.5)
        sy = math.sin(yaw * 0.5)
        cr = math.cos(roll * 0.5)
        sr = math.sin(roll * 0.5)
        cp = math.cos(pitch * 0.5)
        sp = math.sin(pitch * 0.5)

        object_pose.orientation.w = cy * cr * cp + sy * sr * sp
        object_pose.orientation.x = cy * sr * cp - sy * cr * sp
        object_pose.orientation.y = cy * cr * sp + sy * sr * cp
        object_pose.orientation.z = sy * cr * cp - cy * sr * sp        

        userdata.output_object_pose = object_pose
        rospy.loginfo('Succeeded to get pose of the object pos x,y,z %.2f,%.2f,%.2f orient w,x,y,z %.2f,%.2f,%.2f,%.2f',\
            object_pose.position.x, object_pose.position.y, object_pose.position.z,\
            object_pose.orientation.w, object_pose.orientation.x, object_pose.orientation.y, object_pose.orientation.z )
        return 'succeeded'

class getPoseOfTheBox(smach.State):
    def __init__(self):
        smach.State.__init__(self, outcomes=['succeeded', 'aborted'],
                                    output_keys=['output_object_pose'])

        self.namespace = rospy.get_param("~robot_name")
        self.marker_pose_sub = rospy.Subscriber(self.namespace + '/ar_pose_marker', AlvarMarkers, self.arMarkerMsgCallback)

        self.OFFSET_FOR_STRETCH = 0.070
        self.OFFSET_FOR_GOAL_HEIGHT = 0.200

    def arMarkerMsgCallback(self, ar_marker_pose_msg):
        if len(ar_marker_pose_msg.markers) == 0:
            self.ar_marker_pose = False
        else:            
            self.ar_marker_pose = AlvarMarker()
            self.ar_marker_pose = ar_marker_pose_msg.markers[0]

    def execute(self, userdata):
        if self.ar_marker_pose == False:
            rospy.logwarn('Failed to get pose of the marker')
            return 'aborted'
        else:
            object_pose = Pose()
            object_pose.position = self.ar_marker_pose.pose.pose.position
 
            object_pose.position.x += self.OFFSET_FOR_STRETCH
            object_pose.position.y  = 0.0
            object_pose.position.z += self.OFFSET_FOR_GOAL_HEIGHT

            dist = math.sqrt((self.ar_marker_pose.pose.pose.position.x * self.ar_marker_pose.pose.pose.position.x) +
                        (self.ar_marker_pose.pose.pose.position.y * self.ar_marker_pose.pose.pose.position.y))

            if self.ar_marker_pose.pose.pose.position.y > 0:
                yaw = math.acos(self.ar_marker_pose.pose.pose.position.x / dist)
            else:
                yaw = (-1) * math.acos(self.ar_marker_pose.pose.pose.position.x / dist)

            roll = 0.0
            pitch = 0.0

            cy = math.cos(yaw * 0.5)
            sy = math.sin(yaw * 0.5)
            cr = math.cos(roll * 0.5)
            sr = math.sin(roll * 0.5)
            cp = math.cos(pitch * 0.5)
            sp = math.sin(pitch * 0.5)

            object_pose.orientation.w = cy * cr * cp + sy * sr * sp
            object_pose.orientation.x = cy * sr * cp - sy * cr * sp
            object_pose.orientation.y = cy * cr * sp + sy * sr * cp
            object_pose.orientation.z = sy * cr * cp - cy * sr * sp

            userdata.output_object_pose = object_pose
            rospy.loginfo('Succeeded to get pose of the object')
            return 'succeeded'

        self.marker_pose_sub

class getCloserToGoal(smach.State):
    def __init__(self):
        smach.State.__init__(self, outcomes=['succeeded', 'failed'])
        self.namespace = rospy.get_param("~robot_name")
        self.use_platform = rospy.get_param("~use_platform")
        self.object_pose_sub = rospy.Subscriber('/darknet_ros/bounding_boxes', BoundingBoxes, self.darkNetRosMsgCallback)
        self.object_depth_sub = rospy.Subscriber('/camera/aligned_depth_to_color/image_raw', Image, self.depthCameraMsgCallback)
        self.odom_sub = rospy.Subscriber(self.namespace + '/odom', Odometry, self.odomMsgCallback)
        self.cmd_vel_pub = rospy.Publisher(self.namespace + '/cmd_vel', Twist, queue_size=10)
        self.tb3_odom = Odometry()
        self.cmd_vel = Twist()

        self.priv_dist = 0.0
        self.priv_heading = 0.0

        self.objectBoundingBox = BoundingBox()
        self.objectCenX = 0
        self.objectCenY = 0
        self.objectDepth = 0
        self.last_yolodetect_time = rospy.get_rostime() 
        self.bridge = CvBridge() 
        self.objectDepth = 0
        self.objectDetectTime = rospy.get_rostime()

    def depthCameraMsgCallback(self, msg):
        #rospy.logwarn("test")
        try:
            self.cam_depth_img = self.bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
        except CvBridgeError as e:
            print(e)

        height = self.cam_depth_img.shape[0] #1080
        width = self.cam_depth_img.shape[1]  #1920
        if self.objectCenX < width and self.objectCenY < height :
            self.objectDepth = self.cam_depth_img[self.objectCenY, self.objectCenX]
        else :
            self.objectDepth = 0
        #print self.objectDepth

    def darkNetRosMsgCallback(self, msg):
        for i, boundingBox in enumerate(msg.bounding_boxes):
            #print 'boundingBoxe {} {} '.format(i, boundingBox)
            if boundingBox.Class == "bottle" :
                self.objectBoundingBox = boundingBox
                self.objectDetectTime = rospy.get_rostime()
                self.objectCenX = round(self.objectBoundingBox.xmin + self.objectBoundingBox.xmax)/2
                self.objectCenY = round(self.objectBoundingBox.ymin + self.objectBoundingBox.ymax)/2

    def odomMsgCallback(self, odom_msg):       
        self.tb3_odom = odom_msg

    def getDistanceFromRobot(self, goal):
        return goal.pose.pose.position.x
              
    def getAngleBtwRobotAndMarker(self, goal):
        return math.atan2(goal.pose.pose.position.y, goal.pose.pose.position.x)

    def execute(self, userdata):
        while 1:
            if rospy.is_shutdown() :
                return 'failed'

            #return 'succeeded'

            #rospy.sleep(0.1)          
            forwardState = False
            turnState = False
            
            object_detect_duration = rospy.get_rostime().to_sec() - self.objectDetectTime.to_sec()
            rospy.loginfo(" object XY (%d, %d), depth ( %.3f ) timeDuration( %.2f ) ", self.objectCenX, self.objectCenY, self.objectDepth , object_detect_duration)
            
            #check object            
            if object_detect_duration > 1 :
                rospy.loginfo('There is no object')
                continue                     
            
            #Set rotation value
            targetCenX = 652   # 0 ~ 1920 range px
            marginX = 20             
            if targetCenX - self.objectCenX  > 10 :
                rospy.loginfo("turn left ")
                self.cmd_vel.angular.z = 0.05 
            elif targetCenX - self.objectCenX  < -10 :    
                rospy.loginfo("turn right ")
                self.cmd_vel.angular.z = -0.05  
            else :    
                rospy.loginfo("turn zero ")
                self.cmd_vel.angular.z = 0   
                turnState = True

            #Set forward back value
            targetDepth = 0.2 # cm            
            if targetDepth  < self.objectDepth :
                rospy.loginfo("go forward ")
                self.cmd_vel.linear.x = 0.050 
            elif self.objectDepth ==0 or self.objectDepth == None :
                rospy.loginfo("go back ")
                self.cmd_vel.linear.x = -0.050     
            else :    
                rospy.loginfo("go zero ")
                self.cmd_vel.linear.x = 0 
                forwardState = True

            rospy.loginfo(" linear.x %.3f , angular.z %.3f ", self.cmd_vel.linear.x, self.cmd_vel.angular.z )
            self.cmd_vel_pub.publish(self.cmd_vel)  

            #check success  
            if forwardState and turnState :
                rospy.loginfo('finish close obejct')
                return 'succeeded' 

def main():
    rospy.init_node('pick_and_place_state_machine_mnp')
    namespace = rospy.get_param("~robot_name")
    planning_group = rospy.get_param("~planning_group")

    # Create the sub SMACH state machine
    task_center = smach.StateMachine(outcomes=['succeeded','aborted','preempted'])

    # Open the container
    with task_center:

        the_location_of_the_left_room = MoveBaseGoal()
        the_location_of_the_left_room.target_pose.header.frame_id = "map"
        the_location_of_the_left_room.target_pose.header.stamp    = rospy.Time.now()
        the_location_of_the_left_room.target_pose.pose.position.x = -2.0
        the_location_of_the_left_room.target_pose.pose.position.y = 1.0
        the_location_of_the_left_room.target_pose.pose.position.z = 0.0
        the_location_of_the_left_room.target_pose.pose.orientation.w = 0.705
        the_location_of_the_left_room.target_pose.pose.orientation.x = 0.0
        the_location_of_the_left_room.target_pose.pose.orientation.y = 0.0
        the_location_of_the_left_room.target_pose.pose.orientation.z = 0.705

        the_location_of_the_object = MoveBaseGoal()
        the_location_of_the_object.target_pose.header.frame_id = "map"
        the_location_of_the_object.target_pose.header.stamp    = rospy.Time.now()
        the_location_of_the_object.target_pose.pose.position.x = -1.393
        the_location_of_the_object.target_pose.pose.position.y = 3.500
        the_location_of_the_object.target_pose.pose.position.z = 0.0
        the_location_of_the_object.target_pose.pose.orientation.w = 0.705
        the_location_of_the_object.target_pose.pose.orientation.x = 0.0
        the_location_of_the_object.target_pose.pose.orientation.y = 0.0
        the_location_of_the_object.target_pose.pose.orientation.z = 0.705

        # Add states to the container
        '''smach.StateMachine.add('GO_TO_THE_LEFT_ROOM',
                                SimpleActionState(namespace + "/move_base", 
                                                MoveBaseAction,
                                                goal=the_location_of_the_left_room),
                                transitions={'succeeded':'GO_TO_THE_OBJECT'})
                        
        smach.StateMachine.add('GO_TO_THE_OBJECT',
                                SimpleActionState(namespace + "/move_base", 
                                                MoveBaseAction,
                                                goal=the_location_of_the_object),
                                transitions={'succeeded':'GET_CLOSER_TO_OBJECT'})'''
                                                        
        smach.StateMachine.add('GET_CLOSER_TO_OBJECT', getCloserToGoal(),
                                transitions={'succeeded':'PICK',
                                            'failed':'aborted'})

        the_location_of_the_point = MoveBaseGoal()
        the_location_of_the_point.target_pose.header.frame_id = "map"
        the_location_of_the_point.target_pose.header.stamp    = rospy.Time.now()
        the_location_of_the_point.target_pose.pose.position.x = -2.0
        the_location_of_the_point.target_pose.pose.position.y = 1.0
        the_location_of_the_point.target_pose.pose.position.z = 0.0
        the_location_of_the_point.target_pose.pose.orientation.w = 1.0
        the_location_of_the_point.target_pose.pose.orientation.x = 0.0
        the_location_of_the_point.target_pose.pose.orientation.y = 0.0
        the_location_of_the_point.target_pose.pose.orientation.z = 0.0

        the_location_of_the_right_room = MoveBaseGoal()
        the_location_of_the_right_room.target_pose.header.frame_id = "map"
        the_location_of_the_right_room.target_pose.header.stamp    = rospy.Time.now()
        the_location_of_the_right_room.target_pose.pose.position.x = 2.0
        the_location_of_the_right_room.target_pose.pose.position.y = 1.0
        the_location_of_the_right_room.target_pose.pose.position.z = 0.0
        the_location_of_the_right_room.target_pose.pose.orientation.w = 0.705
        the_location_of_the_right_room.target_pose.pose.orientation.x = 0.0
        the_location_of_the_right_room.target_pose.pose.orientation.y = 0.0
        the_location_of_the_right_room.target_pose.pose.orientation.z = 0.705

        the_location_of_the_box = MoveBaseGoal()
        the_location_of_the_box.target_pose.header.frame_id = "map"
        the_location_of_the_box.target_pose.header.stamp    = rospy.Time.now()
        the_location_of_the_box.target_pose.pose.position.x = 0.766
        the_location_of_the_box.target_pose.pose.position.y = 3.670
        the_location_of_the_box.target_pose.pose.position.z = 0.0
        the_location_of_the_box.target_pose.pose.orientation.w = 0.705
        the_location_of_the_box.target_pose.pose.orientation.x = 0.0
        the_location_of_the_box.target_pose.pose.orientation.y = 0.0
        the_location_of_the_box.target_pose.pose.orientation.z = 0.705

        smach.StateMachine.add('GO_TO_THE_TURN_AROUND_POINT',
                                SimpleActionState(namespace + "/move_base", 
                                                MoveBaseAction,
                                                goal=the_location_of_the_point),
                                transitions={'succeeded':'GO_TO_THE_RIGHT_ROOM'})

        smach.StateMachine.add('GO_TO_THE_RIGHT_ROOM',
                                SimpleActionState(namespace + "/move_base", 
                                                MoveBaseAction,
                                                goal=the_location_of_the_right_room),
                                transitions={'succeeded':'GO_TO_THE_BOX'})

        smach.StateMachine.add('GO_TO_THE_BOX',
                                SimpleActionState(namespace + "/move_base", 
                                                MoveBaseAction,
                                                goal=the_location_of_the_box),
                                transitions={'succeeded':'GET_CLOSER_TO_BOX'})
                            
        smach.StateMachine.add('GET_CLOSER_TO_BOX', getCloserToGoal(),
                                transitions={'succeeded':'PLACE',
                                            'failed':'aborted'})

        # Create the sub SMACH state machine
        pick_center = smach.StateMachine(outcomes=['succeeded','aborted','preempted'])

        with pick_center:
            pick_center.userdata.planning_group = planning_group

            def joint_position_request_cb(userdata, request):
                joint = JointPosition()
                joint.position = userdata.input_position
                joint.max_velocity_scaling_factor = 1.0
                joint.max_accelerations_scaling_factor = 1.0

                request.planning_group = userdata.input_planning_group
                request.joint_position = joint
                return request

            def joint_position_response_cb(userdata, response):
                if response.is_planned == False:
                    return 'aborted'
                else:
                    rospy.sleep(3.)
                    return 'succeeded'

            def eef_pose_request_cb(userdata, request):
                eef = KinematicsPose()
                eef.pose = userdata.input_pose
                rospy.loginfo('eef.position.x : %f', eef.pose.position.x)
                rospy.loginfo('eef.position.y : %f', eef.pose.position.y)
                rospy.loginfo('eef.position.z : %f', eef.pose.position.z)
                eef.max_velocity_scaling_factor = 1.0
                eef.max_accelerations_scaling_factor = 1.0
                eef.tolerance = userdata.input_tolerance

                request.planning_group = userdata.input_planning_group
                request.kinematics_pose = eef
                return request

            def align_arm_with_object_response_cb(userdata, response):
                if response.is_planned == False:
                    pick_center.userdata.align_arm_with_object_tolerance += 0.005
                    rospy.logwarn('Set more tolerance[%f]', pick_center.userdata.align_arm_with_object_tolerance)
                    return 'aborted'
                else:
                    #OFFSET_FOR_STRETCH = 0.030
                    OFFSET_FOR_STRETCH = 0.020
                    pick_center.userdata.object_pose.position.x += OFFSET_FOR_STRETCH
                    rospy.sleep(3.)
                    return 'succeeded'

            def close_to_object_response_cb(userdata, response):
                if response.is_planned == False:
                    pick_center.userdata.close_to_object_tolerance += 0.005
                    rospy.logwarn('Set more tolerance[%f]', pick_center.userdata.close_to_object_tolerance)
                    return 'aborted'
                else:
                    OFFSET_FOR_OBJECT_HEIGHT = 0.020
                    pick_center.userdata.object_pose.position.z += OFFSET_FOR_OBJECT_HEIGHT
                    rospy.sleep(3.)
                    return 'succeeded'

            def pick_up_object_response_cb(userdata, response):
                if response.is_planned == False:
                    pick_center.userdata.pick_up_object_tolerance += 0.005
                    rospy.logwarn('Set more tolerance[%f]', pick_center.userdata.pick_up_object_tolerance)
                    return 'aborted'
                else:
                    rospy.sleep(3.)
                    return 'succeeded'

            def gripper_request_cb(userdata, request):
                joint = JointPosition()
                joint.position = userdata.input_gripper
                joint.max_velocity_scaling_factor = 1.0
                joint.max_accelerations_scaling_factor = 1.0

                request.planning_group = userdata.input_planning_group
                request.joint_position = joint
                return request

            def gripper_response_cb(userdata, response):
                rospy.sleep(1.)
                return 'succeeded'

            pick_center.userdata.object_pose = Pose()
            smach.StateMachine.add('GET_POSE_OF_THE_OBJECT', getPoseOfTheObject(),
                                    transitions={'succeeded':'SET_INIT_POSITION',
                                                'aborted':'aborted'},
                                    remapping={'output_object_pose':'object_pose'})                

            pick_center.userdata.init_position = [0.0, -0.65, 1.20, -0.54]
            smach.StateMachine.add('SET_INIT_POSITION',
                                    ServiceState(planning_group + '/moveit/set_joint_position',
                                                    SetJointPosition,
                                                    request_cb=joint_position_request_cb,
                                                    response_cb=joint_position_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_position']),
                                   transitions={'succeeded':'OPEN_GRIPPER'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_position':'init_position'})

            pick_center.userdata.open_gripper = [0.15]
            smach.StateMachine.add('OPEN_GRIPPER',
                                    ServiceState(namespace + '/gripper',
                                                    SetJointPosition,
                                                    request_cb=gripper_request_cb,
                                                    response_cb=gripper_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_gripper']),
                                   #transitions={'succeeded':'GET_POSE_OF_THE_OBJECT'},
                                   transitions={'succeeded':'ALIGN_ARM_WITH_OBJECT'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_gripper':'open_gripper'})

            pick_center.userdata.align_arm_with_object_tolerance = 0.01
            smach.StateMachine.add('ALIGN_ARM_WITH_OBJECT',
                                    ServiceState(planning_group + '/moveit/set_kinematics_pose',
                                                    SetKinematicsPose,
                                                    request_cb=eef_pose_request_cb,
                                                    response_cb=align_arm_with_object_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_pose',
                                                                'input_tolerance']),                                                    
                                   transitions={'succeeded':'CLOSE_TO_OBJECT',
                                                'aborted':'ALIGN_ARM_WITH_OBJECT'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_pose':'object_pose',
                                            'input_tolerance':'align_arm_with_object_tolerance'})

            pick_center.userdata.close_to_object_tolerance = 0.01
            smach.StateMachine.add('CLOSE_TO_OBJECT',
                                    ServiceState(planning_group + '/moveit/set_kinematics_pose',
                                                    SetKinematicsPose,
                                                    request_cb=eef_pose_request_cb,
                                                    response_cb=close_to_object_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_pose',
                                                                'input_tolerance']),                                                    
                                   transitions={'succeeded':'GRIP_OBJECT',
                                                'aborted':'CLOSE_TO_OBJECT'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_pose':'object_pose',
                                            'input_tolerance':'close_to_object_tolerance'})

            pick_center.userdata.close_gripper = [0.0]
            smach.StateMachine.add('GRIP_OBJECT',
                                    ServiceState(namespace + '/gripper',
                                                    SetJointPosition,
                                                    request_cb=gripper_request_cb,
                                                    response_cb=gripper_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_gripper']),
                                   transitions={'succeeded':'PICK_UP_OBJECT'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_gripper':'close_gripper'})

            pick_center.userdata.pick_up_object_tolerance = 0.01
            smach.StateMachine.add('PICK_UP_OBJECT',
                                    ServiceState(planning_group + '/moveit/set_kinematics_pose',
                                                    SetKinematicsPose,
                                                    request_cb=eef_pose_request_cb,
                                                    response_cb=pick_up_object_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_pose',
                                                                'input_tolerance']),                                                    
                                   transitions={'succeeded':'SET_HOLDING_POSITION',
                                                'aborted':'PICK_UP_OBJECT'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_pose':'object_pose',
                                            'input_tolerance':'pick_up_object_tolerance'})

            pick_center.userdata.holding_position = [0.0, -1.5707, 1.37, -0.20]
            smach.StateMachine.add('SET_HOLDING_POSITION',
                                    ServiceState(planning_group + '/moveit/set_joint_position',
                                                    SetJointPosition,
                                                    request_cb=joint_position_request_cb,
                                                    response_cb=joint_position_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_position']),
                                   transitions={'succeeded':'succeeded'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_position':'holding_position'})

        smach.StateMachine.add('PICK', pick_center,
                                transitions={'succeeded':'GO_TO_THE_TURN_AROUND_POINT', 'aborted':'aborted'})

        # Create the sub SMACH state machine
        place_center = smach.StateMachine(outcomes=['succeeded','aborted','preempted'])

        with place_center:
            place_center.userdata.planning_group = planning_group

            def joint_position_request_cb(userdata, request):
                joint = JointPosition()
                joint.position = userdata.input_position
                joint.max_velocity_scaling_factor = 1.0
                joint.max_accelerations_scaling_factor = 1.0

                request.planning_group = userdata.input_planning_group
                request.joint_position = joint
                return request

            def joint_position_response_cb(userdata, response):
                if response.is_planned == False:
                    return 'aborted'
                else:
                    rospy.sleep(3.)
                    return 'succeeded'

            def eef_pose_request_cb(userdata, request):
                eef = KinematicsPose()
                eef.pose = userdata.input_pose
                rospy.loginfo('eef.position.x : %f', eef.pose.position.x)
                rospy.loginfo('eef.position.y : %f', eef.pose.position.y)
                rospy.loginfo('eef.position.z : %f', eef.pose.position.z)
                eef.max_velocity_scaling_factor = 1.0
                eef.max_accelerations_scaling_factor = 1.0
                eef.tolerance = userdata.input_tolerance

                request.planning_group = userdata.input_planning_group
                request.kinematics_pose = eef
                return request

            def close_to_box_response_cb(userdata, response):
                if response.is_planned == False:
                    pick_center.userdata.close_to_box_tolerance += 0.005
                    rospy.logwarn('Set more tolerance[%f]', pick_center.userdata.close_to_box_tolerance)
                    return 'aborted'
                else:
                    rospy.sleep(3.)
                    return 'succeeded'

            def gripper_request_cb(userdata, request):
                joint = JointPosition()
                joint.position = userdata.input_gripper
                joint.max_velocity_scaling_factor = 1.0
                joint.max_accelerations_scaling_factor = 1.0

                request.planning_group = userdata.input_planning_group
                request.joint_position = joint
                return request

            def gripper_response_cb(userdata, response):
                rospy.sleep(1.)
                return 'succeeded'

            place_center.userdata.ready_position = [0.0, -1.05, 0.35, 0.70]
            smach.StateMachine.add('SET_INIT_POSITION',
                                    ServiceState(planning_group + '/moveit/set_joint_position',
                                                    SetJointPosition,
                                                    request_cb=joint_position_request_cb,
                                                    response_cb=joint_position_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_position']),
                                   transitions={'succeeded':'GET_POSE_OF_THE_BOX'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_position':'ready_position'})

            place_center.userdata.box_pose = Pose()
            smach.StateMachine.add('GET_POSE_OF_THE_BOX', getPoseOfTheBox(),
                                    transitions={'succeeded':'CLOSE_TO_BOX',
                                                'aborted':'aborted'},
                                    remapping={'output_object_pose':'box_pose'})
                                
            place_center.userdata.close_to_box_tolerance = 0.01
            smach.StateMachine.add('CLOSE_TO_BOX',
                                    ServiceState(planning_group + '/moveit/set_kinematics_pose',
                                                    SetKinematicsPose,
                                                    request_cb=eef_pose_request_cb,
                                                    response_cb=close_to_box_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_pose',
                                                                'input_tolerance']),                                                    
                                   transitions={'succeeded':'PLACE_OBJECT',
                                                'aborted':'CLOSE_TO_BOX'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_pose':'box_pose',
                                            'input_tolerance':'close_to_box_tolerance'})

            place_center.userdata.open_gripper = [0.15]
            smach.StateMachine.add('PLACE_OBJECT',
                                    ServiceState(namespace + '/gripper',
                                                    SetJointPosition,
                                                    request_cb=gripper_request_cb,
                                                    response_cb=gripper_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_gripper']),
                                   transitions={'succeeded':'SET_HOME_POSITION'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_gripper':'open_gripper'})

            place_center.userdata.init_position = [0.0, -1.5707, 1.37, 0.2258]
            smach.StateMachine.add('SET_HOME_POSITION',
                                    ServiceState(planning_group + '/moveit/set_joint_position',
                                                    SetJointPosition,
                                                    request_cb=joint_position_request_cb,
                                                    response_cb=joint_position_response_cb,
                                                    input_keys=['input_planning_group',
                                                                'input_position']),
                                   transitions={'succeeded':'succeeded'},
                                   remapping={'input_planning_group':'planning_group',
                                            'input_position':'init_position'})

        smach.StateMachine.add('PLACE', place_center,
                                transitions={'succeeded':'succeeded', 'aborted':'aborted'})


    sis = smach_ros.IntrospectionServer('server_name', task_center, '/TASKS_CENTER')
    sis.start()

    # Execute SMACH plan
    outcome = task_center.execute()

    # Wait for ctrl-c to stop the application
    rospy.spin()
    sis.stop()

if __name__ == '__main__':
    main()
